spring:
    profiles:
        active: local
    application:
        name: newsfeed-api

    jackson:
        default-property-inclusion: non_null
        time-zone: Asia/Seoul
        date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
        serialization:
            write-dates-as-timestamps: false
        deserialization:
            fail-on-unknown-properties: false

    cache:
        type: redis
        redis:
            time-to-live: 1800000  # 30? (ms)
            cache-null-values: false

    data:
        redis:
            host: localhost
            port: 6379
            database: 0
            timeout: 2000ms
            jedis:
                pool:
                    max-active: 10
                    max-idle: 10
                    min-idle: 1
                    max-wait: 2000ms

    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            file-size-threshold: 2KB

server:
    port: 8080
    servlet:
        context-path: /
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
        min-response-size: 1024
    http2:
        enabled: true

aws:
    region: ap-northeast-2
    dynamodb:
        endpoint:  ${DYNAMODB_ENDPOINT}
    sqs:
        news-feed-fanout-queue-url: ${NEWS_FEED_FANOUT_QUEUE_URL:}
        notification-queue-url: ${NOTIFICATION_QUEUE_URL:}
        like-count-queue-url: ${LIKE_COUNT_QUEUE_URL:}
    sns:
        post-events-topic-arn: ${POST_EVENTS_TOPIC_ARN:}

jwt:
    secret: mySecretKey123456789mySecretKey123456789mySecretKey123456789
    expiration: 86400000         # 24?? (ms)
    refresh-expiration: 2592000000  # 30? (ms)

app:
    version: 1.0.0
    upload:
        max-file-size: 104857600  # 100MB
        allowed-file-types: jpg,jpeg,png,gif,mp4,mov
    rate-limit:
        requests-per-minute: 100
        requests-per-hour: 1000

logging:
    level:
        com.newsfeed: INFO
        org.springframework.security: DEBUG
        org.springframework.cache: DEBUG
        software.amazon.awssdk: WARN
        org.springframework.data.redis: DEBUG
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file:
        name: logs/newsfeed-api.log
        max-size: 10MB
        max-history: 30

management:
    endpoints:
        web:
            exposure:
                include: health,info,metrics,prometheus,env
            base-path: /actuator
    endpoint:
        health:
            show-details: when-authorized
            show-components: always
    metrics:
        export:
            cloudwatch:
                namespace: NewsFeed/API
                batch-size: 20
                step: 1m
                enabled: true
    health:
        redis:
            enabled: true
        diskspace:
            enabled: true

springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html
        display-request-duration: true
        groups-order: DESC
        operations-sorter: method
        disable-swagger-default-url: true
        use-root-path: true
        show-actuator: true

resilience4j:
    circuitbreaker:
        instances:
            post-event-handler:
                registerHealthIndicator: true
                slidingWindowSize: 10
                slidingWindowType: COUNT_BASED
                minimumNumberOfCalls: 5
                failureRateThreshold: 50
                waitDurationInOpenState: 30s
                slowCallRateThreshold: 100
                slowCallDurationThreshold: 60s
                permittedNumberOfCallsInHalfOpenState: 3
                automaticTransitionFromOpenToHalfOpenEnabled: true
            newsfeed-fanout:
                registerHealthIndicator: true
                slidingWindowSize: 20
                slidingWindowType: COUNT_BASED
                minimumNumberOfCalls: 10
                failureRateThreshold: 30
                waitDurationInOpenState: 60s
                slowCallRateThreshold: 100
                slowCallDurationThreshold: 30s
                permittedNumberOfCallsInHalfOpenState: 5
                automaticTransitionFromOpenToHalfOpenEnabled: true
    retry:
        instances:
            post-event-handler:
                maxRetryAttempts: 3
                waitDuration: 2s
                enableExponentialBackoff: true
                exponentialBackoffMultiplier: 2
                retryExceptions:
                    - java.io.IOException
                    - java.util.concurrent.TimeoutException
                    - org.springframework.dao.OptimisticLockingFailureException
                ignoreExceptions:
                    - java.lang.IllegalArgumentException
            newsfeed-fanout:
                maxRetryAttempts: 2
                waitDuration: 1s
                enableExponentialBackoff: true
                exponentialBackoffMultiplier: 1.5
                retryExceptions:
                    - java.io.IOException
                    - java.util.concurrent.TimeoutException
                ignoreExceptions:
                    - java.lang.IllegalArgumentException

---

spring:
    config:
        activate:
            on-profile: local
    data:
        redis:
            host: localhost
            port: 6379

aws:
    region: ap-northeast-2
    dynamodb:
        endpoint: http://localhost:8000
    sqs:
        news-feed-fanout-queue-url: news-feed-fanout-queue
        notification-queue-url: notification-queue
        like-count-queue-url: like-count-queue
    sns:
        post-events-topic-arn: arn:aws:sns:ap-northeast-2:123456789012:post-events-topic

jwt:
    secret: localDevelopmentSecretKeyForTestingPurposeOnly123456789

logging:
    level:
        com.newsfeed: DEBUG
        org.springframework.web: DEBUG
        org.springframework.security: DEBUG

---

spring:
    config:
        activate:
            on-profile: test
    data:
        redis:
            host: localhost
            port: 6379
            database: 1

aws:
    region: us-east-1
    dynamodb:
        endpoint: http://localhost:8000
    sqs:
        news-feed-fanout-queue-url: test-news-feed-fanout-queue
        notification-queue-url: test-notification-queue
        like-count-queue-url: test-like-count-queue
    sns:
        post-events-topic-arn: arn:aws:sns:us-east-1:123456789012:test-post-events-topic

jwt:
    secret: testSecretKeyForUnitTestingPurposeOnly123456789
    expiration: 3600000  # 1??

logging:
    level:
        com.newsfeed: DEBUG
        org.springframework.test: DEBUG

---

spring:
    config:
        activate:
            on-profile: prod
    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT:6379}
            timeout: 3000ms

aws:
    region: ap-northeast-2

jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}

logging:
    level:
        com.newsfeed: INFO
        org.springframework: WARN
        software.amazon.awssdk: ERROR
    file:
        name: /var/log/newsfeed/application.log

management:
    metrics:
        export:
            cloudwatch:
                enabled: true
                namespace: NewsFeed/Production
                batch-size: 20

---

spring:
    config:
        activate:
            on-profile: lambda
    main:
        lazy-initialization: true  # Lambda 콜드 스타트 최적화
        
aws:
    region: ${AWS_REGION:ap-northeast-2}
    
jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}
    
# Lambda 환경에서는 CloudWatch가 자동으로 로그를 수집하므로 최소한의 설정만 사용
logging:
    level:
        com.khu.acc.newsfeed: INFO
        com.amazonaws: WARN
        org.springframework: WARN
        software.amazon.awssdk: WARN
    pattern:
        console: "[%level] %logger{36} - %msg%n"  # 간결한 패턴
        
management:
    endpoints:
        web:
            exposure:
                include: health  # Lambda에서는 health check만 노출
    metrics:
        export:
            cloudwatch:
                enabled: true
                namespace: NewsFeed/Lambda
                batch-size: 10  # Lambda의 짧은 실행 시간 고려