service: news-feed

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  environment:
    FOLLOW_TABLE_NAME: Follows
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource: arn:aws:dynamodb:ap-northeast-2:662074586333:table/Follows

functions:
  followService:
    handler: handler.handler
    events:
      - http:
          path: /{proxy+}
          method: any

